name: Generate Bundler 1.x Gemfile.lock

on:
  workflow_dispatch: {}
  push:
    paths:
      - Gemfile
      - .github/workflows/generate-lockfile.yml

permissions:
  contents: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      # Upgrade RubyGems so older runners don't choke on transitive deps
      - name: Upgrade RubyGems (>= 3.3.22)
        run: |
          gem update --system 3.3.26

      - name: Install Bundler 1.17.3
        run: |
          gem uninstall bundler -aIx || true
          gem install bundler -v 1.17.3

      - name: Generate Gemfile.lock (Bundler 1.17.3)
        run: |
          bundle _1.17.3_ install --without development test

      - name: Commit lockfile if changed
        run: |
          if git status --porcelain | grep -q "Gemfile.lock"; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add Gemfile.lock
            git commit -m "Add Gemfile.lock (Bundler 1.17.3) for Morph.io"
            git push
          else
            echo "No changes to commit."
          fi
